### ISSUE TITLE
Is there anyway to use the view with sqlalchemy??

### ISSUE THREAD

**Issue by ghost** [jklukas/sqlalchemy-views#2]
with your package I can create and drop views .
but how can I query and filter data in database views???

**Comment by jklukas** [comment]
A `Table` object in sqlalchemy can reference either a table or a view. So there should be no syntactic difference between querying a view vs. a table.

The only reason that this package is necessary is that `CREATE VIEW` and `DROP VIEW` actually require different syntax. In a `SELECT` statement, there's nothing to distinguish how you query a table vs. a view, so sqlalchemy doesn't need to know if the relation is a table or an object in that case.
