### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by ryanermita** [jklukas/sqlalchemy-views#3]
The codebase was updated last 3 years ago.
is this still compatible with `SQLAlchemy version 1.2.0b3` ?

**Comment by jklukas** [comment]
The amount of code involved is minimal and extends a quite stable part of the SQLAlchemy API, so I see no reason compatibility will break anytime soon.

Would it be helpful to document that expectation in the README? Any other thoughts on how to make it clear that this is still active?

**Comment by jklukas** [comment]
Added https://github.com/jklukas/sqlalchemy-views/blob/master/README.rst#status

**Comment by ryanermita** [comment]
Thank you @jklukas ! I appreciate your work! :+1:
